[PERF-299] Add sample script using TestNG framework
saucelabs/extended-debugging-JAVA-examples pull request #1
Opened 2019-01-03 13:38 UTC by farhan-sauce

Ticket: [PERF-299](https://saucedev.atlassian.net/browse/PERF-299)

2019-01-03 19:42 UTC, yfangsl requested changes
So while this generally seems fine as a demonstration of how to use custom commands, I'm not sure this is what the story was actually about, and I'm not sure it can be properly finished at the moment.  I think the story was about the *new* performance command that uses the baseline metrics.  So more based on the examples here: https://wiki.saucelabs.com/display/DEVTOOLS/Automated+Performance+Assertion

2019-01-03 19:42 UTC, yfangsl commented on TestNG/src/test/java/com/yourcompany/Pages/SauceDemoPage.java
> +    public Map getPeroformance() {
getPerformance

2019-01-03 19:42 UTC, yfangsl commented on TestNG/src/test/java/com/yourcompany/Tests/PerformanceTest.java
> +        Map<String, Object> performance = page.getPeroformance();
getPerformance

2019-01-04 09:05 UTC, farhan-sauce commented
@yfangs Did we deploy `baseline metrics` custom command yet? I thought [this ticket](https://saucedev.atlassian.net/browse/PERF-291) is still a blocker and we decided to add baseline metrics assertion later once we deploy it.

I would be happy to use new performance command if it is already deployed and there is no blocker.

2019-01-15 17:53 UTC, seanenright commented
@farhan-sauce @yfangsl merging so we can close the ticket (per christine).
there is a follow up ticket to update each of the sample scripts with the new custom command 
https://saucedev.atlassian.net/browse/PERF-353

2019-01-15 17:53 UTC, merged